# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My Test Blog
email: wiwijaja@googlemail.com
description: This is a test blog using jekyll
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://WilBerlin.github.io" # the base hostname & protocol for your site
github_username:  WilBerlin

# Build settings
markdown: kramdown
